FROM dunglas/frankenphp:php8.3-bookworm

RUN install-php-extensions pdo_mysql gd

WORKDIR /app

COPY . /app

EXPOSE 8080

CMD ["sh", "-c", "frankenphp php-server --listen :${PORT:-8080} --root /app"]
