<?php
require_once __DIR__ . '/../../includes/functions.php'; require_once __DIR__ . '/../../config/database.php';
$slug=trim($_GET['slug']??''); if(!$slug){http_response_code(404);die(t('errors.article_not_found'));}
$st=db()->prepare('SELECT p.*,u.full_name author_name FROM blog_posts p LEFT JOIN users u ON u.id=p.author_id WHERE p.slug=? AND p.status="published" LIMIT 1');$st->execute([$slug]);$post=$st->fetch();if(!$post){http_response_code(404);die(t('errors.article_not_found'));}
db()->prepare('UPDATE blog_posts SET views_count=views_count+1 WHERE id=?')->execute([$post['id']]);
$rel=db()->prepare('SELECT title,slug,cover_path,category FROM blog_posts WHERE category=? AND id<>? AND status="published" ORDER BY published_at DESC LIMIT 3');$rel->execute([$post['category'],$post['id']]);$related=$rel->fetchAll();
function render_blog_body_pro(string $body): string { $safe=e($body);$lines=preg_split('/
+/', $safe);$html='';foreach($lines as $line){$line=trim($line);if($line==='')continue;if(preg_match('/^###\s+(.*)$/',$line,$m))$html.='<h3>'.$m[1].'</h3>';elseif(preg_match('/^##\s+(.*)$/',$line,$m))$html.='<h2>'.$m[1].'</h2>';elseif(preg_match('/^#\s+(.*)$/',$line,$m))$html.='<h2>'.$m[1].'</h2>';else $html.='<p>'.$line.'</p>';}return $html;}
function blog_public_cover2(?string $path): string {if($path&&preg_match('#^assets/uploads/[A-Za-z0-9._/-]+$#',$path)&&is_file(__DIR__.'/../../'.$path))return APP_URL.'/'.$path;return real_image('blog-default','blog-default');}
$pageTitle=$post['title'];require_once __DIR__.'/../../includes/header.php';
?>
<div class="article-page"><div class="container section--tight"><div class="article-top"><?php echo back_button(APP_URL.'/pages/blog/index.php','','solid');?><div class="article-breadcrumb"><a href="<?php echo APP_URL;?>/">Home</a><span>›</span><a href="<?php echo APP_URL;?>/pages/blog/index.php">Blog</a><span>›</span><span><?php echo e($post['category']??'Article');?></span></div></div>
<header class="article-header"><span class="article-kicker"><?php echo e($post['category']??'Marketplace');?></span><h1><?php echo e($post['title']);?></h1><p><?php echo e($post['excerpt']??'');?></p><div class="article-meta"><span>By <?php echo e($post['author_name']??'IsokoRyacu');?></span><span>•</span><span><?php echo e(time_ago($post['published_at']));?></span><span>•</span><span><?php echo number_format((int)$post['views_count']);?> views</span></div></header>
<div class="article-cover"><img src="<?php echo e(blog_public_cover2($post['cover_path']??null));?>" alt="<?php echo e($post['title']);?>"></div><div class="article-layout"><main class="article-body"><?php echo render_blog_body_pro($post['body']);?></main><aside class="article-side"><div class="article-side__box"><strong>On this article</strong><p>Useful marketplace information from IsokoRyacu.</p><a class="btn btn--secondary" href="<?php echo APP_URL;?>/pages/blog/index.php">More articles</a></div></aside></div>
<?php if($related):?><section class="article-related"><div class="section__head"><div><h2 class="section__title">You may also like</h2><p class="section__sub">More guides from the marketplace journal.</p></div></div><div class="blog-related-grid"><?php foreach($related as $r):?><a class="blog-card-pro" href="<?php echo APP_URL;?>/pages/blog/post.php?slug=<?php echo e($r['slug']);?>"><div class="blog-card-pro__media"><img loading="lazy" src="<?php echo e(blog_public_cover2($r['cover_path']??null));?>" alt="<?php echo e($r['title']);?>"><span><?php echo e($r['category']??'Marketplace');?></span></div><div class="blog-card-pro__body"><h2><?php echo e($r['title']);?></h2><div class="blog-read">Read article <span>→</span></div></div></a><?php endforeach;?></div></section><?php endif;?></div></div>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>