-- Market-store payment provider configuration (admin-managed)
INSERT IGNORE INTO site_settings (setting_key, setting_value, description) VALUES
('payment_mtn_enabled','0','Enable MTN MoMo payments'),
('payment_mtn_environment','sandbox','MTN MoMo environment: sandbox or production'),
('payment_mtn_api_user','', 'Encrypted MTN API user'),
('payment_mtn_api_key','', 'Encrypted MTN API key'),
('payment_mtn_subscription_key','', 'Encrypted MTN subscription key'),
('payment_mtn_callback_url','', 'MTN callback URL'),
('payment_airtel_enabled','0','Enable Airtel Money payments'),
('payment_airtel_environment','sandbox','Airtel Money environment: sandbox or production'),
('payment_airtel_client_id','', 'Encrypted Airtel client ID'),
('payment_airtel_client_secret','', 'Encrypted Airtel client secret'),
('payment_airtel_callback_url','', 'Airtel callback URL'),
('payment_card_enabled','0','Enable card payments'),
('payment_card_provider','stripe','Card payment provider'),
('payment_card_publishable_key','', 'Card publishable key'),
('payment_card_secret_key','', 'Encrypted card secret key'),
('payment_card_webhook_secret','', 'Encrypted card webhook signing secret'),
('payment_card_callback_url','', 'Card webhook/callback URL'),
('payment_bank_enabled','0','Enable bank payment integration'),
('payment_bank_provider','', 'Bank payment provider name'),
('payment_bank_merchant_id','', 'Encrypted bank merchant ID'),
('payment_bank_api_key','', 'Encrypted bank API key'),
('payment_bank_api_secret','', 'Encrypted bank API secret'),
('payment_bank_callback_url','', 'Bank callback URL'),
('payment_crypto_enabled','0','Enable crypto payments'),
('payment_crypto_provider','', 'Crypto payment provider'),
('payment_crypto_api_key','', 'Encrypted crypto API key'),
('payment_crypto_api_secret','', 'Encrypted crypto API secret'),
('payment_crypto_webhook_secret','', 'Encrypted crypto webhook secret'),
('payment_crypto_callback_url','', 'Crypto callback URL'),
('payment_platform_fee_percent','5','Default marketplace platform/removal protection fee percentage');
